export type BeaconType = {
  created_date: Date | string | null;
  modified_date: Date | string | null;
  bc_id: number | null;
  bc_index: string | null;
  bc_management: number | null;
  bc_address: string;
  bc_description: string | null;
  bc_used_type: 0 | 1 | 2;
  bc_battery_remain: string | null;
  bc_battery_time: Date | null;
  bc_scn_group: string | null;
  bc_receive_time: Date | null;
  bc_io_state: string | null;
  bc_input_time: Date | null;
  bc_out_time: Date | null;
  bc_pos_x: number | null;
  bc_emergency: number;
  ts_index: string | null;
  wk_id?: number;
  wk_index?: string;
  wk_name?: string;
  wk_phone?: string;
  wk_tel?: null;
  wk_position?: string;
  wk_nation?: string;
  wk_birth?: Date;
  wk_blood_type?: number;
  wk_blood_group?: number;
  wk_sms_yn?: number;
  wk_image?: null;
  wk_io_state?: string;
  co_id?: number;
  te_index?: string;
  co_main?: number;
  co_name?: string;
  co_sectors?: null;
  co_description?: null;
  te_id?: number;
  te_name?: string;
};

export type BleType = {
  bc_id: number;
  bc_index: string;
  bc_management: number;
  created_date: Date;
  modified_date: null;
  bc_address: string;
  bc_description: null;
  bc_used_type: number;
  bc_battery_remain: string;
  bc_battery_time: Date;
  bc_scn_group: string;
  bc_receive_time: Date;
  bc_io_state: string;
  bc_input_time: Date;
  bc_out_time: null;
  bc_pos_x: null;
  bc_sos_time: null;
  bc_emergency: number;
  bc_sos_action: number;
  ts_index: string;
  wk_id: number;
  wk_index: string;
  wk_name: string;
  wk_phone: string;
  wk_tel: null;
  wk_position: string;
  wk_nation: string;
  wk_birth: Date;
  wk_blood_type: number;
  wk_blood_group: number;
  wk_sms_yn: number;
  wk_image: null;
  wk_io_state: string;
  wk_co_id: number;
  wk_ts_index: string;
  wk_te_index: null;
  wk_co_name: string;
  vh_id: null;
  vh_index: null;
  vh_name: null;
  vh_number: null;
  vh_image: null;
  vh_io_state: null;
  vh_description: null;
  vh_co_id: null;
  vh_ts_index: null;
  vh_te_index: null;
  vh_co_name: null;
  scn_id: number;
  scn_pos_x: number;
  scn_group: string;
  scn_address: string;
  local_index: string;
  local_entrance: string;
  local_name: string;
  local_area: number;
  local_type: number;
  group_id: number;
  group_name: string;
  group_pos_x: number;
  group_kind: number;
};
