import { asyncActions } from 'lib/reducerUtils';

export const [
  GET_SENSORS,
  GET_SENSORS_PENDING,
  GET_SENSORS_FULFILLED,
  GET_SENSORS_REJECTED,
] = asyncActions('sensors/GET_SENSORS');

export const [GET_SENSOR, GET_SENSOR_PENDING, GET_SENSOR_FULFILLED, GET_SENSOR_REJECTED] =
  asyncActions('sensors/GET_SENSOR');

export const [
  POST_SENSOR,
  POST_SENSOR_PENDING,
  POST_SENSOR_FULFILLED,
  POST_SENSOR_REJECTED,
] = asyncActions('sensors/POST_SENSOR');

export const [PUT_SENSOR, PUT_SENSOR_PENDING, PUT_SENSOR_FULFILLED, PUT_SENSOR_REJECTED] =
  asyncActions('sensors/PUT_SENSOR');

export const [
  DELETE_SENSOR,
  DELETE_SENSOR_PENDING,
  DELETE_SENSOR_FULFILLED,
  DELETE_SENSOR_REJECTED,
] = asyncActions('sensors/DELETE_SENSOR');

export const [
  POST_ALARM_SEARCH,
  POST_ALARM_SEARCH_PENDING,
  POST_ALARM_SEARCH_FULFILLED,
  POST_ALARM_SEARCH_REJECTED,
] = asyncActions('sensors/POST_ALARM_SEARCH');

export const [
  GET_ALARM_LIMIT,
  GET_ALARM_LIMIT_PENDING,
  GET_ALARM_LIMIT_FULFILLED,
  GET_ALARM_LIMIT_REJECTED,
] = asyncActions('sensors/GET_ALARM_LIMIT');

export const [
  POST_SENSOR_RECORD,
  POST_SENSOR_RECORD_PENDING,
  POST_SENSOR_RECORD_FULFILLED,
  POST_SENSOR_RECORD_REJECTED,
] = asyncActions('sensors/POST_SENSOR_RECORD');

export const [
  PUT_IMAGE_SENSOR,
  PUT_IMAGE_SENSOR_PENDING,
  PUT_IMAGE_SENSOR_FULFILLED,
  PUT_IMAGE_SENSOR_REJECTED,
] = asyncActions('sensors/PUT_IMAGE_SENSOR');
