export type SensorType = {
  sensor_id: number | null;
  sensor_index: string | null;
  created_date: Date | string | null;
  modified_date: Date | string | null;
  sensor_pos_x: number | null;
  alarm_path: string | null;
  sensor_name: string | null;
  sensor_start_time: Date | string | null;
  sensor_stop_time: Date | string | null;
  record_time: Date | string | null;
  o2_value: number | null;
  o2_state_code: number | null;
  h2s_value: number | null;
  h2s_state_code: number | null;
  co_value: number | null;
  co_state_code: number | null;
  voc_value: number | null;
  voc_state_code: number | null;
  comb_value: number | null;
  comb_state_code: number | null;
  sensor_state_code: number | null;
  sensor_image: string | null;
  sensor_number: number | null;
  sensor_ip: string | null;
  sensor_port: number | null;
  local_index: string | null;
  sensor_danger_action: number | null;
  sensor_danger_time: Date | string | null;
  sensor_action: number | null;
  action: number | null;
  net_scan_action: number | null;
  net_scan_time: Date | string | null;
  net_start_time: Date | string | null;
  net_stop_time: Date | string | null;
  net_state: string | null;
  device_code: number | null;
  gas_id: number | null;
  gas_code: string | null;
  gas_name: string | null;
  gas_unit: string | null;
  range_min: number | null;
  range_max: number | null;
  normal_low: number | null;
  normal_high: number | null;
  warning1_low: number | null;
  warning1_high: number | null;
  warning2_low: number | null;
  warning2_high: number | null;
  danger1_low: number | null;
  danger1_high: number | null;
  danger2_low: number | null;
  danger2_high: number | null;
  local_id: number | null;
  local_entrance: string | null;
  local_name: string | null;
  local_used: number | null;
  local_type: number | null;
  local_area: number | null;
  local_number: number | null;
  monitor_number: number | null;
  ts_index: string | null;
};

export type SensorErrorType = {
  sensor_ip: string | null;
  sensor_port: number | null;
  voc_error: string | null;
  comb_error: string | null;
  o2_error: string | null;
  h2s_error: string | null;
  co_error: string | null;
  sensor_image: string | null;
};

export type SensorSearchType = {
  local_index: string | null;
};
