export type DeviceType = {
  created_date: Date;
  modified_date: null;
  device_id: number;
  device_index: string;
  device_name: string;
  device_pos_x: number;
  device_ip: string;
  device_port: number;
  device_image: null;
  net_scan_action: number;
  net_state: string;
  net_scan_time: Date;
  net_start_time: Date;
  net_stop_time: null;
  device_code: number;
  local_index: string;
  local_name: string;
  local_area: number;
  local_number: number;
  local_type: number;
  local_entrance: null;
  ts_index: string;
};
