export type SiteType = {
  // [key: string]: string | number | boolean | Date | null;
  ts_id?: number;
  ts_index?: string | null;
  created_date?: Date | string | null;
  modified_date?: Date | string | null;
  ts_main_title: string | null;
  ts_sub_title?: string | null;
  nms_action: number;
  cctv_action: number;
  gas_action: number;
  phone_action: number;
  wifi_action: number;
  tts_action: number;
  sos_action: number;
  lamp_action: number;
  wireless_action: number;
  ts_plan_length: number;
  ts_description: string | null;
  ble_type: number;
  dig_type: number;
  dig_length_type: number;
  ts_url: string | null;
  te_index: string | null;
  sta_start_point: string | null;
  sta_end_point: string | null;
  qr_action: number;
  did_action: number;
  area_action: number;
  cctv_tab: number;
  te_id: number;
  te_name: string | null;
  te_logo: string | null;
  te_logo_2: string | null;
  te_description: string | null;
  te_color: string | null;
};
